# MicroPython: Ingeniería de Aprendizaje con LEGO SPIKE
# El Framework del Docente Arquitecto
# Licensed under CC BY-NC-ND 4.0 - Diego Saavedra 2026
project:
  type: book
  output-dir: docs
  resources: 
    - "images/*.png"

book:
  title: "MicroPython: Ingeniería de Aprendizaje"
  subtitle: "Maestría para el Docente Arquitecto"
  author: "Diego Saavedra"
  output-file: "micropython_ingenieria"
  date: today
  date-format: medium
  favicon: favicon.ico
  description: "Despliegue de sistemas de aprendizaje con MicroPython y LEGO SPIKE Prime."
  keyword: "MicroPython, Ingeniería, LEGO, SPIKE Prime, Python, Educación, Statick"
  
  reader-mode: true
  search: true
  
  sidebar: 
    logo: images/robot-espi32-cartoon.png
    search: true
    collapse-level: 1
  
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  
  cover-image: images/robot-espi32-cartoon.png
  
  page-footer:
    border: true
    left: |
      © Diego Saavedra
    center: |
      Arquitectura del Conocimiento - Abacom
    right: |
      Built with [Quarto](https://quarto.org/)
  
  chapters:
    - index.qmd
    - about.qmd
    - license.qmd
    - part: "EL MANIFIESTO DEL ARQUITECTO"
      chapters:
        - contenido/unidad0/competencias_docente.qmd
    - part: "FASE 1: INFRAESTRUCTURA Y ENTORNO"
      chapters:
        - contenido/unidad1/1_instalacion_pybricks.qmd
        - contenido/unidad1/lab1_hola_mundo.qmd
        - quizzes/quiz_unidad1.qmd
    - part: "FASE 2: INTERFACES Y CONTROL VISUAL"
      chapters:
        - contenido/unidad2/1_display_luces.qmd
        - contenido/unidad2/lab2_animaciones.qmd
        - quizzes/quiz_unidad2.qmd
    - part: "FASE 3: SISTEMAS DE TRACCIÓN Y MOTORES"
      chapters:
        - contenido/unidad3/1_motores.qmd
        - contenido/unidad3/lab3_navegacion.qmd
        - quizzes/quiz_unidad3.qmd
    - part: "FASE 4: PERCEPCIÓN Y TELEMETRÍA"
      chapters:
        - contenido/unidad4/1_sensores.qmd
        - contenido/unidad4/lab4_telemetria.qmd
        - quizzes/quiz_unidad4.qmd
    - part: "FASE 5: DESPLIEGUE FINAL (PROYECTO)"
      chapters:
        - contenido/unidad5/1_proyecto_final.qmd
        - quizzes/quiz_unidad5.qmd

format:
  html:
    theme: 
      - solar
      - theme.scss
    css: css/styles.css
    bootstrap-version: 5
    toc: true
    number-sections: false
    include-in-header:
      text: |
        <script src="https://cdn.jsdelivr.net/npm/quizdown@latest/public/build/quizdown.js"></script>
        <script>quizdown.init();</script>

execute:
  echo: true
  enabled: false
